---
resources:
- name: resources
  type: git
  source:
    uri: https://github.com/timlharrison/concourse_test.git

jobs:
- name: script
  public: true
  plan:
  - get: resources
    trigger: true
  - task: pipeline_script
    file: resources/pipeline_task.yml
