---
resources:
- name: resources
  type: git
  source:
    uri: https://github.com/timlharrison/concourse_test.git

jobs:
- name: job-test-app
  public: true
  plan:
  - get: resources
    trigger: true
  - task: web-app-tests
    file: resource-tutorial/tutorials/basic/job-inputs/task_run_tests.yml
